### PR TITLE
Travis no docker

### PR DESCRIPTION
**Pull request by Eoksni**
Experiment to see how much time can we save (if any) if we don't use docker at all for build&test

### CODE REVIEW

**Comment by Eoksni** [comment]
The speed difference is there without any doubts. ~3 min with docker, and less than 2 min without docker. I don't know if we should give up on docker though. As our project grows, the build time will grow, and the complexity of travis configuration will also grow if it doesn't use docker. But time difference still be the same - 1 minute. It is also possible to optimize a little bit the docker version of build by reusing dev image and by caching yarn and node_modules and reusing them in the dev image. I expect ~15 sec time decrease. So it would be only 45 seconds difference in exchange of no future problems with travis configuration no matter how complex our project becomes. Seems like a fair deal.

**Comment by Eoksni** [comment]
@ITarako I think we should close this pull request, but not delete branch in case in future we decide to make use of no-docker builds. Let me know what you think.

**Comment by ITarako** [comment]
you made an interesting experiment. yes, leave the branch, maybe docker will follow npm ^^
I will add a easy issue for cache in current milestone

**Comment by Eoksni** [comment]
nah, docker is fine :)

**Pull request closed without merging**
