### PR TITLE
V0.4

### PR DESCRIPTION
**Pull request by ITarako**

### CODE REVIEW

**Comment by Eoksni** [comment]
misplaced labels
image

**Comment by Eoksni** [comment]
with 
```
    "db": "memory",
```
in `config.json`, deleted items are restored after page refresh (f5)

**Comment by ITarako** [comment]
i don't see bug with restored

**Comment by ITarako** [comment]
why in this PullRequest `Merge pull request #72 from emotz/FixesForV0.4`  and  `fixed linter errors` look like one commit

**Comment by Eoksni** [comment]
ehm... those are two different commits
image
what do you mean "they look like one commit"

**Comment by Eoksni** [comment]
"i don't see bug" -> "can't reproduce bug"

**Comment by Eoksni** [comment]
If you add item, delete it right away, then f5 - item is gone.
But if you add item, f5, then delete it, then f5 again - item is restored.
with this config.json
```
{
    "default_language": "ru",
    "db": "memory",
    "db_url": "mongodb://localhost:27017/kladovka",
    "express_port": 8080
}
```

**Comment by ITarako** [comment]
Confused the commits, all is ok

**Comment by ITarako** [comment]
test for bug of restored in process

**Pull request merged**
